version: "3.8"

services:
  battlestation:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - ion-cannon-1
      - ion-cannon-2
      - ion-cannon-3
    networks:
      - battlenet

  ion-cannon-1:
    build:
      context: .
      dockerfile: cmd/mock-ion-cannon/Dockerfile
    environment:
      - GENERATION=1
      - FIRE_TIME=3.5
    ports:
      - "8081:8080"
    networks:
      - battlenet

  ion-cannon-2:
    build:
      context: .
      dockerfile: cmd/mock-ion-cannon/Dockerfile
    environment:
      - GENERATION=2
      - FIRE_TIME=1.5
    ports:
      - "8082:8080"
    networks:
      - battlenet

  ion-cannon-3:
    build:
      context: .
      dockerfile: cmd/mock-ion-cannon/Dockerfile
    environment:
      - GENERATION=3
      - FIRE_TIME=2.5
    ports:
      - "8083:8080"
    networks:
      - battlenet

networks:
  battlenet:
    driver: bridge
